apiVersion: v1
kind: Pod
metadata:
  name: api-gateway-proxy
  labels:
    app: api-gateway-proxy
spec:
  containers:
    - name: apigateway
      imagePullPolicy: Never
      image: bhavanipandranki/nodejs-api-gateway:0.1.0
      ports:
        - containerPort: 3001