apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: user-service-proxy
  ports:
    - name: user-service-proxy
      protocol: TCP
      port: 3002
      targetPort: 3002